apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: llama-server
  namespace: default
spec:
  jobName: "llama-server"
  scrapeInterval: 5s
  httpSDConfigs:
    - url: "http://host.docker.internal:9091/targets.json"
      refreshInterval: 5s
  relabelings:
    - sourceLabels:
        - llama_model_id
      targetLabel: __param_model
    - sourceLabels:
        - __param_autoload
      targetLabel: __param_autoload
      replacement: "false"
