{
 "title": "LLM Metrics Dashboard",
 "tags": [
  "llama",
  "llm"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Prompt Processing Rate (t/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "avg"
       },
       "type": "query"
      }
     ],
     "downsampler": "mean",
     "expression": "($B > 0) * $A / (($B > 0) * $B + ($B == 0) * 1) ",
     "reducer": "mean",
     "type": "math",
     "upsampler": "fillna"
    }
   ]
  },
  {
   "title": "Token Generation Rate (t/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expression": "($B > 0) * $A / (($B > 0) * $B + ($B == 0) * 1) ",
     "type": "math"
    }
   ]
  },
  {
   "title": "Prompt Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(llamacpp:prompt_tokens_total[$__rate_interval])",
     "legendFormat": "{{llama_model_id}}"
    }
   ]
  },
  {
   "title": "Generated Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(llamacpp:tokens_predicted_total[$__rate_interval])",
     "legendFormat": "{{llama_model_id}}"
    }
   ]
  },
  {
   "title": "Prompt Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(llamacpp:prompt_seconds_total[$__rate_interval])",
     "legendFormat": "{{llama_model_id}}"
    }
   ]
  },
  {
   "title": "Token Generation Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "increase(llamacpp:tokens_predicted_seconds_total[$__rate_interval])",
     "legendFormat": "{{llama_model_id}}"
    }
   ]
  },
  {
   "title": "llama_decode()",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(llamacpp:n_decode_total{}[$__rate_interval])",
     "legendFormat": "{{llama_model_id}}"
    }
   ]
  },
  {
   "title": "Concurrent Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "llamacpp:requests_processing", "legendFormat": "{{llama_model_id}}" }
   ]
  },
  {
   "title": "Context Watermark",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "llamacpp:n_tokens_max", "legendFormat": "{{llama_model_id}}" }
   ]
  }
 ]
}